site_name: Matillion Docs
nav:
  - Home: 'index.md'
  - Release notes:
      - 'Matillion ETL 1.64': '164-patch-notes.md'
  - Destinations:
      - 'Snowflake': 'connect-to-snowflake.md'
      - 'BigQuery':
        - 'Set up BigQuery': 'set-up-google-bigquery.md'
        - 'Connect to BigQuery': 'connect-to-bigquery.md'
  - Pipelines:
    - 'MySQL': 'mysql.md'
  - Previews:
    - 'Test': 'test.md'

theme: 
  name: 'material'
  palette:
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  features:
    - navigation.expand 
    - navigation.instant
    - navigation.prune
    - navigation.top
    - navigation.tracking

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/shortcuts.js

copyright: Copyright &copy; 2022 - Matillion


extra:
  generator: false
